import '/imc_calculator/models/imc_indicator.dart';

class ImcTable {
  List<ImcIndicator> men = [
    const ImcIndicator(
      age: ImcBounds(2, 2),
      imcUnderWeight: ImcBounds(0, 14.4),
      imcNormalWeight: ImcBounds(14.41, 17.8),
      imcOverWeight: ImcBounds(17.81, 18.8),
      imcObesityWeight: ImcBounds(18.81, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(3, 3),
      imcUnderWeight: ImcBounds(0, 14.3),
      imcNormalWeight: ImcBounds(14.31, 17.2),
      imcOverWeight: ImcBounds(17.21, 18.0),
      imcObesityWeight: ImcBounds(18.01, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(4, 4),
      imcUnderWeight: ImcBounds(0, 13.9),
      imcNormalWeight: ImcBounds(13.91, 16.8),
      imcOverWeight: ImcBounds(16.81, 17.8),
      imcObesityWeight: ImcBounds(17.81, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(5, 5),
      imcUnderWeight: ImcBounds(0, 13.7),
      imcNormalWeight: ImcBounds(13.71, 16.9),
      imcOverWeight: ImcBounds(16.91, 18.2),
      imcObesityWeight: ImcBounds(18.21, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(6, 6),
      imcUnderWeight: ImcBounds(0, 13.65),
      imcNormalWeight: ImcBounds(13.66, 17.3),
      imcOverWeight: ImcBounds(17.31, 18.7),
      imcObesityWeight: ImcBounds(18.71, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(7, 7),
      imcUnderWeight: ImcBounds(0, 13.7),
      imcNormalWeight: ImcBounds(13.71, 17.6),
      imcOverWeight: ImcBounds(17.61, 19.6),
      imcObesityWeight: ImcBounds(19.61, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(8, 8),
      imcUnderWeight: ImcBounds(0, 13.8),
      imcNormalWeight: ImcBounds(13.81, 18.3),
      imcOverWeight: ImcBounds(18.31, 20.5),
      imcObesityWeight: ImcBounds(20.51, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(9, 9),
      imcUnderWeight: ImcBounds(0, 14.1),
      imcNormalWeight: ImcBounds(14.11, 19.0),
      imcOverWeight: ImcBounds(19.01, 21.6),
      imcObesityWeight: ImcBounds(21.61, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(10, 10),
      imcUnderWeight: ImcBounds(0, 14.4),
      imcNormalWeight: ImcBounds(14.41, 19.47),
      imcOverWeight: ImcBounds(19.71, 22.7),
      imcObesityWeight: ImcBounds(22.71, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(11, 11),
      imcUnderWeight: ImcBounds(0, 14.8),
      imcNormalWeight: ImcBounds(14.81, 20.5),
      imcOverWeight: ImcBounds(20.51, 23.7),
      imcObesityWeight: ImcBounds(23.71, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(12, 12),
      imcUnderWeight: ImcBounds(0, 15.3),
      imcNormalWeight: ImcBounds(15.31, 21.4),
      imcOverWeight: ImcBounds(21.41, 24.7),
      imcObesityWeight: ImcBounds(24.71, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(13, 13),
      imcUnderWeight: ImcBounds(0, 15.65),
      imcNormalWeight: ImcBounds(15.66, 22.2),
      imcOverWeight: ImcBounds(22.21, 25.5),
      imcObesityWeight: ImcBounds(25.51, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(14, 14),
      imcUnderWeight: ImcBounds(0, 16.3),
      imcNormalWeight: ImcBounds(16.31, 23.1),
      imcOverWeight: ImcBounds(23.11, 26.4),
      imcObesityWeight: ImcBounds(26.41, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(15, 15),
      imcUnderWeight: ImcBounds(0, 16.8),
      imcNormalWeight: ImcBounds(16.81, 23.8),
      imcOverWeight: ImcBounds(23.81, 27.3),
      imcObesityWeight: ImcBounds(27.31, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(16, 16),
      imcUnderWeight: ImcBounds(0, 17.4),
      imcNormalWeight: ImcBounds(17.41, 24.5),
      imcOverWeight: ImcBounds(24.51, 27.8),
      imcObesityWeight: ImcBounds(27.81, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(17, 17),
      imcUnderWeight: ImcBounds(0, 18),
      imcNormalWeight: ImcBounds(18.01, 25.4),
      imcOverWeight: ImcBounds(25.41, 28.5),
      imcObesityWeight: ImcBounds(28.51, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(18, 18),
      imcUnderWeight: ImcBounds(0, 18.5),
      imcNormalWeight: ImcBounds(18.51, 26),
      imcOverWeight: ImcBounds(26.01, 29.3),
      imcObesityWeight: ImcBounds(29.31, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(19, 19),
      imcUnderWeight: ImcBounds(0, 19.0),
      imcNormalWeight: ImcBounds(19.01, 26.8),
      imcOverWeight: ImcBounds(26.81, 30.3),
      imcObesityWeight: ImcBounds(30.31, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(20, 20),
      imcUnderWeight: ImcBounds(0, 19.5),
      imcNormalWeight: ImcBounds(19.51, 27.2),
      imcOverWeight: ImcBounds(27.21, 30.6),
      imcObesityWeight: ImcBounds(30.61, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(21, double.infinity),
      imcUnderWeight: ImcBounds(0, 18.49),
      imcNormalWeight: ImcBounds(18.5, 24.9),
      imcOverWeight: ImcBounds(25, 29.9),
      imcObesityWeight: ImcBounds(30, double.infinity),
    ),
  ];

  List<ImcIndicator> women = [
    const ImcIndicator(
      age: ImcBounds(2, 2),
      imcUnderWeight: ImcBounds(0, 14.2),
      imcNormalWeight: ImcBounds(14.21, 17.5),
      imcOverWeight: ImcBounds(17.51, 18.6),
      imcObesityWeight: ImcBounds(18.61, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(3, 3),
      imcUnderWeight: ImcBounds(0, 13.8),
      imcNormalWeight: ImcBounds(13.81, 16.9),
      imcOverWeight: ImcBounds(16.91, 18.1),
      imcObesityWeight: ImcBounds(18.11, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(4, 4),
      imcUnderWeight: ImcBounds(0, 13.6),
      imcNormalWeight: ImcBounds(13.61, 16.8),
      imcOverWeight: ImcBounds(16.81, 18.1),
      imcObesityWeight: ImcBounds(18.11, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(5, 5),
      imcUnderWeight: ImcBounds(0, 13.5),
      imcNormalWeight: ImcBounds(13.51, 16.9),
      imcOverWeight: ImcBounds(16.91, 18.5),
      imcObesityWeight: ImcBounds(18.51, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(6, 6),
      imcUnderWeight: ImcBounds(0, 13.4),
      imcNormalWeight: ImcBounds(13.41, 17.3),
      imcOverWeight: ImcBounds(17.31, 19.2),
      imcObesityWeight: ImcBounds(19.21, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(7, 7),
      imcUnderWeight: ImcBounds(0, 13.5),
      imcNormalWeight: ImcBounds(13.51, 17.9),
      imcOverWeight: ImcBounds(17.91, 20.1),
      imcObesityWeight: ImcBounds(20.11, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(8, 8),
      imcUnderWeight: ImcBounds(0, 13.6),
      imcNormalWeight: ImcBounds(13.61, 18.7),
      imcOverWeight: ImcBounds(18.71, 21.2),
      imcObesityWeight: ImcBounds(21.21, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(9, 9),
      imcUnderWeight: ImcBounds(0, 13.9),
      imcNormalWeight: ImcBounds(13.91, 19.5),
      imcOverWeight: ImcBounds(19.51, 22.4),
      imcObesityWeight: ImcBounds(22.41, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(10, 10),
      imcUnderWeight: ImcBounds(0, 14.2),
      imcNormalWeight: ImcBounds(14.21, 20.4),
      imcOverWeight: ImcBounds(20.41, 23.5),
      imcObesityWeight: ImcBounds(23.51, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(11, 11),
      imcUnderWeight: ImcBounds(0, 14.6),
      imcNormalWeight: ImcBounds(14.61, 21.3),
      imcOverWeight: ImcBounds(21.31, 24.7),
      imcObesityWeight: ImcBounds(24.71, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(12, 12),
      imcUnderWeight: ImcBounds(0, 15.1),
      imcNormalWeight: ImcBounds(15.11, 22.1),
      imcOverWeight: ImcBounds(22.11, 25.7),
      imcObesityWeight: ImcBounds(25.71, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(13, 13),
      imcUnderWeight: ImcBounds(0, 15.5),
      imcNormalWeight: ImcBounds(15.51, 22.9),
      imcOverWeight: ImcBounds(22.91, 26.7),
      imcObesityWeight: ImcBounds(26.71, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(14, 14),
      imcUnderWeight: ImcBounds(0, 16.1),
      imcNormalWeight: ImcBounds(16.61, 23.7),
      imcOverWeight: ImcBounds(23.71, 27.7),
      imcObesityWeight: ImcBounds(27.71, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(15, 15),
      imcUnderWeight: ImcBounds(0, 16.5),
      imcNormalWeight: ImcBounds(16.51, 24.3),
      imcOverWeight: ImcBounds(24.31, 28.5),
      imcObesityWeight: ImcBounds(28.51, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(16, 16),
      imcUnderWeight: ImcBounds(0, 17),
      imcNormalWeight: ImcBounds(17.01, 24.9),
      imcOverWeight: ImcBounds(24.91, 29.3),
      imcObesityWeight: ImcBounds(29.31, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(17, 17),
      imcUnderWeight: ImcBounds(0, 17.4),
      imcNormalWeight: ImcBounds(17.41, 25.4),
      imcOverWeight: ImcBounds(25.41, 29.9),
      imcObesityWeight: ImcBounds(29.91, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(18, 18),
      imcUnderWeight: ImcBounds(0, 17.7),
      imcNormalWeight: ImcBounds(17.71, 25.9),
      imcOverWeight: ImcBounds(25.91, 30.7),
      imcObesityWeight: ImcBounds(30.71, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(19, 19),
      imcUnderWeight: ImcBounds(0, 17.8),
      imcNormalWeight: ImcBounds(17.81, 26.3),
      imcOverWeight: ImcBounds(26.31, 31.4),
      imcObesityWeight: ImcBounds(31.41, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(20, 20),
      imcUnderWeight: ImcBounds(0, 17.8),
      imcNormalWeight: ImcBounds(17.81, 26.5),
      imcOverWeight: ImcBounds(26.51, 31.7),
      imcObesityWeight: ImcBounds(31.71, double.infinity),
    ),
    const ImcIndicator(
      age: ImcBounds(21, double.infinity),
      imcUnderWeight: ImcBounds(0, 18.49),
      imcNormalWeight: ImcBounds(18.5, 24.9),
      imcOverWeight: ImcBounds(25, 29.9),
      imcObesityWeight: ImcBounds(30, double.infinity),
    ),
  ];
}
